name: Yanqiao Zhan
link: https://github.com/nkuclassical
author: Yanqiao Zhan
email: zhanyanqiao@126.com
github: nkuclassical

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough", "with_toc_data"]

pygments: true
permalink: none
